/**
 * GameProtocol — all game-specific message send functions.
 *
 * Mirrors the structure of MessageService but for game messages only.
 * Each function builds a signed, nonce-stamped packet and sends it.
 *
 * Message types defined here:
 *   game_start  — broadcast when all peers are ready, carries gameId + startsAt
 *   move        — a player submits a UCI move
 *   game_over   — broadcast when the game ends
 */

import { Peer, PeerStatus } from '../network/peer.js';
import { signMessage }      from '../protocol/verifysignsignature.js';
import { randomUUID }       from 'crypto';
import { logger }           from '../utils/logger.js';
import { Team, GameResult } from './game-state.js';
import { WebSocket }        from 'ws';

// ---------------------------------------------------------------------------
// Wire format — every game message on the network looks like this:
//
//  {
//    payload: {
//      key:        <senderPublicKey>,   // who sent it
//      type:       <messageType>,       // "game_start" | "move" | "game_over"
//      gameId:     <uuid>,              // which game this belongs to
//      timestamp:  <epochMs>,           // sender's synchronized time
//      nonce:      <uuid>,              // replay protection
//      ... type-specific fields ...
//    },
//    signature: <base64 ed25519>        // signs JSON.stringify(payload)
//  }
//
// ---------------------------------------------------------------------------

function buildPacket(payload: object, privateKey: string): string {
    const message   = JSON.stringify(payload);
    const signature = signMessage(message, privateKey);
    return JSON.stringify({ payload, signature });
}

function sendToAll(packet: string, peers: Map<string, Peer>, label: string): void {
    for (const [peerId, peer] of peers) {
        if (peer.status === PeerStatus.Alive && peer.socket.readyState === WebSocket.OPEN) {
            try {
                peer.socket.send(packet);
            } catch (err) {
                logger.error(`Failed to send ${label}`, {
                    peer:    peerId.slice(0, 8),
                    message: err instanceof Error ? err.message : String(err),
                });
            }
        }
    }
}

// ---------------------------------------------------------------------------
// game_start
// ---------------------------------------------------------------------------
// Broadcast by EVERY node once it determines all peers are ready.
// The receiving side collects game_start messages from all peers and
// uses them to confirm consensus on gameId and startsAt.
//
// Fields:
//   gameId       — UUID generated by the time-master node (lowest key).
//                  All other nodes use the gameId received from the master.
//   resolvedTeam — this node's final team after resolution algorithm.
//   startsAt     — epoch ms when the game begins (synchronized time).
//   totalPlayers — how many players are in this game.

export interface GameStartPayload {
    key:          string;
    type:         'game_start';
    gameId:       string;
    resolvedTeam: Team;
    startsAt:     number;
    totalPlayers: number;
    timestamp:    number;
    nonce:        string;
}

export function sendGameStart(
    peers:        Map<string, Peer>,
    myPublicKey:  string,
    myPrivateKey: string,
    gameId:       string,
    resolvedTeam: Team,
    startsAt:     number,
    totalPlayers: number,
): void {
    const payload: GameStartPayload = {
        key:          myPublicKey,
        type:         'game_start',
        gameId,
        resolvedTeam,
        startsAt,
        totalPlayers,
        timestamp:    Date.now(),
        nonce:        randomUUID(),
    };
    const packet = buildPacket(payload, myPrivateKey);
    sendToAll(packet, peers, 'game_start');
    logger.info(`Broadcast game_start`, {
        gameId:      gameId.slice(0, 8),
        team:        resolvedTeam,
        startsAt:    new Date(startsAt).toISOString(),
    });
}

// ---------------------------------------------------------------------------
// move
// ---------------------------------------------------------------------------
// Sent by the node whose turn it is.
// Broadcast to ALL peers (not just the opponent) so spectators/observers
// and future global-network relays can track the game.
//
// Fields:
//   gameId     — must match the active game.
//   moveIndex  — 0-based ply counter. Receiving side rejects if out-of-order.
//   move       — UCI format: "e2e4", "d7d8q" (promotion appended).
//   fenBefore  — FEN of the board BEFORE this move. Receiver verifies this
//                matches their own board — catches any state divergence early.
//   fenAfter   — FEN of the board AFTER this move. Receiver verifies after
//                applying the move locally. Second line of defence.
//   team       — sender's team ('white' | 'black'). Receiver rejects if it's
//                not this team's turn.

export interface MovePayload {
    key:        string;
    type:       'move';
    gameId:     string;
    moveIndex:  number;
    move:       string;     // UCI e.g. "e2e4"
    fenBefore:  string;
    fenAfter:   string;
    team:       Team;
    timestamp:  number;
    nonce:      string;
}

export function sendMove(
    peers:        Map<string, Peer>,
    myPublicKey:  string,
    myPrivateKey: string,
    gameId:       string,
    moveIndex:    number,
    move:         string,
    fenBefore:    string,
    fenAfter:     string,
    team:         Team,
): void {
    const payload: MovePayload = {
        key:       myPublicKey,
        type:      'move',
        gameId,
        moveIndex,
        move,
        fenBefore,
        fenAfter,
        team,
        timestamp: Date.now(),
        nonce:     randomUUID(),
    };
    const packet = buildPacket(payload, myPrivateKey);
    sendToAll(packet, peers, 'move');
    logger.info(`Move sent`, {
        index: moveIndex,
        move,
        fen:   fenAfter.split(' ')[0], // board part only
    });
}

// ---------------------------------------------------------------------------
// game_over
// ---------------------------------------------------------------------------
// Broadcast by any node that detects the game has ended (checkmate, draw,
// stalemate). Also sent by a node that is resigning.
//
// Fields:
//   gameId    — must match the active game.
//   result    — { winner: 'white' | 'black' | 'draw' | null,
//                 reason: 'checkmate' | 'stalemate' | 'resignation' |
//                         'disconnect' | 'draw_agreement' }
//   lastFen   — final board position for record-keeping.
//   moveCount — number of half-moves played.

export interface GameOverPayload {
    key:       string;
    type:      'game_over';
    gameId:    string;
    result:    GameResult;
    lastFen:   string;
    moveCount: number;
    timestamp: number;
    nonce:     string;
}

export function sendGameOver(
    peers:        Map<string, Peer>,
    myPublicKey:  string,
    myPrivateKey: string,
    gameId:       string,
    result:       GameResult,
    lastFen:      string,
    moveCount:    number,
): void {
    const payload: GameOverPayload = {
        key:       myPublicKey,
        type:      'game_over',
        gameId,
        result,
        lastFen,
        moveCount,
        timestamp: Date.now(),
        nonce:     randomUUID(),
    };
    const packet = buildPacket(payload, myPrivateKey);
    sendToAll(packet, peers, 'game_over');
    logger.info(`Broadcast game_over`, {
        gameId:    gameId.slice(0, 8),
        winner:    result.winner,
        reason:    result.reason,
        moveCount,
    });
}
